### PR TITLE
Initial checkin for supporting MaxVersion in SemVerStrategyState

### PR DESCRIPTION
**Pull request by dlethin**
Next step is to define some version strategies that make use of it

### CODE REVIEW

**Comment by ajoberstar** [comment]
Overall, this code looks good, but I'd like to play out the idea of reusing NearestVersionLocator some more. I'll throw together my own PR for this and we can see what the best next steps will be.

**Comment by ajoberstar** [comment]
Just created #118 for my alternate impl. Still need to push up the tests for it. However, I don't think that approach is going to work very well. Without understanding what the branches are being used for, it's hard (maybe impossible) to know whether parallel development should override the nearest.

**Comment by kknd22** [comment]
any movements on this? i think this might sholve one of my issue:  
https://github.com/ajoberstar/gradle-git/issues/202

**Comment by ajoberstar** [comment]
See my comment on #202 .

**Comment by ajoberstar** [comment]
I still want to address this, but given how long this PR's been open, I'm going to close. The original issue is still open.

**Pull request closed without merging**
