### PR TITLE
fix #196: prepareGhPages deletes files in the root directory instead …

### LINKED ISSUE #196: prepareGhPages deletes files in the root directory instead of those in the target directory
A preliminary action of the prepareGhPages task consists in deleting all files in the target directory (that is, the directory configured using `into`).
However, this doesn't work as expected: the current implementation creates a list containing the names of the files found in the target directory and then removes the corresponding files found in the root of the gh-pages branch of the repositiory.
Moreover, files in subdirectories of the target directory are ignored.

I will send a PR that fixes this issue.

### PR DESCRIPTION
**Pull request by siordache**
…of those in the target directory

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm pretty sure this was resolved by #192. Please correct me if I'm wrong. I do like how you switched around the logic to avoid unnecessary work.

> `toRemove << path.relativize(f.toPath()).toString().replaceAll('\\\\', '/')`

This part seems like it should be handled by grgit rather than this plugin. I don't think it's this plugin's job to fix paths.

**Comment by siordache** [comment]
You're right. I'm closing this PR.

**Comment by siordache** [comment]
I have sent to grgit a PR that adds support for paths with backslashes.

**Comment by mojavelinux** [comment]
Thanks @siordache!!

**Pull request closed without merging**
