### PR TITLE
Added configurable TagHandler (fixes #83)

### LINKED ISSUE #83: Feature request: configurable tag prefix
It would be nice if the tag prefix could be configured to something other than 'v'
Filtering for that prefix when resolving earlier versions void be very useful too.
That would make it possible to use the release plugin on a project where there is multiple different "products" in the same git repository, with each their own release/version cycle.

### PR DESCRIPTION
**Pull request by hierynomus**

### CODE REVIEW

**Comment by hierynomus** [comment]
Hi Andrew, here's the proposed implementation. This would allow you to configure a different TagHandler to parse/create the tags.

**Comment by ajoberstar** [comment]
Thanks! I'll try to take an in-depth look this weekend.

**Comment by hierynomus** [comment]
Hi Andrew,
Did you manage to have a look over the weekend?

Thx!

**Comment by ajoberstar** [comment]
Sorry, didn't get a chance. Might have some time tomorrow. Otherwise, with the holidays, it might not be for a week or so.

**Comment by ajoberstar** [comment]
Sorry for the delay. I finally got a chance to look at this.

I've been a little wary of solutions to this, since they seem to exacerbate the complexity issues that are already there. However, I think this is pretty close to as good as we can get given the constraints of backwards compatibility.

The one thing I'd like to change is the separation of `TagHandler` from `TagStrategy`. Putting the `parseTag`/`toTagString` methods within `TagStrategy` would avoid the cyclical dependency. These could be as simple as `Closure` fields.

What do you think?

**Comment by hierynomus** [comment]
No problems. I've changed the PR as indicated. Let me know whether I need to improve something else.

**Comment by hierynomus** [comment]
And fixed the new test that came from the merged PR :smile:

**Comment by ajoberstar** [comment]
Looks good. Thanks!

**Pull request merged**
