### PR TITLE
github-pages: fix patterns used for removing files

### PR DESCRIPTION
**Pull request by siordache**
Fixes issue #196 .

### CODE REVIEW

**Comment by ajoberstar** [comment]
Thanks!

**Comment by siordache** [comment]
Could you please make a patch release that contain this PR? I have a few projects that depend on it.
Thanks!

**Comment by ajoberstar** [comment]
It might be a couple days. I need to re-review what stuff is included in this one, looks like I have a few other un-released PRs that are already merged in. Want to make sure that stuff is all ready to go before doing a release.

**Comment by siordache** [comment]
OK, thanks!

**Comment by ajoberstar** [comment]
Sorry for the delay, the RC (1.6.0-rc.1) is out now.

**Comment by siordache** [comment]
Thanks a lot!

**Pull request merged**
